# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Kittens Mom", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Meta Description",
          name: "meta_description",
          widget: "string",
          required: false,
        }

      - {
          label: "Litters Description",
          name: "body",
          widget: "markdown",
          required: true,
        }
      - {
          label: "Additional Info",
          name: "info",
          widget: "markdown",
          required: false,
        }
      - {
          label: "Reserved",
          name: "reserved",
          widget: "boolean",
          default: false,
        }

    # PAGES
